server:
  port: ${port:9000}


spring:
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    platform: mysql
    url: jdbc:mysql://dungiapp.ctezwyeyfqua.ap-northeast-2.rds.amazonaws.com/cj?autoReconnect=true
    username: dungiapp
    password: dungiapp
    driver-class-name: com.mysql.cj.jdbc.Driver

secret:
  kakao:
    restApiKey: 1941893462dfad4f46b2ccc179a60d07
    clientKey: DzRwMyq97w8G4U8jDoBfhNjylQjMX8eV
    callbackUrl: https://wowwewe.herokuapp.com/user/kakao/callback

